# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uId', models.CharField(default=users.models.getUserId, max_length=200, unique=True)),
                ('entityId', models.TextField(blank=True, null=True)),
                ('userType', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('emailid', models.EmailField(max_length=254, null=True, unique=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('switchrole', models.BooleanField(default=False)),
                ('primaryrole', models.TextField(blank=True, null=True)),
                ('secondaryrole', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('parentUserName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.CharField(default=users.models.getUserTypeId, max_length=200, unique=True)),
                ('entityId', models.TextField(blank=True, null=True)),
                ('typeName', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('defaultPreference', models.TextField(blank=True, null=True)),
                ('assignPreferences', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
                ('modifiedBy', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='userTypeUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
    ]
