# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersextrafield'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersextrafield',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
