# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersextrafield_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=b'')),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
                ('modifiedBy', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('uId', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Users', to_field='uId')),
            ],
        ),
    ]
