# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usersfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFileUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='usersfiles',
            name='tId',
            field=models.CharField(default=users.models.getuserFileId, max_length=200, unique=True),
        ),
    ]
