# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180504_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersfiles',
            old_name='tId',
            new_name='fId',
        ),
    ]
