# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180504_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='resetpassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resetlink', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('uId', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Users', to_field='uId')),
            ],
        ),
    ]
