# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_emailverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverify',
            name='isVerify',
            field=models.BooleanField(default=False),
        ),
    ]
